### ISSUE TITLE
File path analysis problem

### ISSUE THREAD

**Issue by iceberg2271** [l3ger0j/Questopia#27]
When I use this version，[2.4.0](https://github.com/seedhartha/QuestPlayer/releases/tag/2.4.0)

It can be used normally when there is a case difference in the file path.
such as filename is /xxx/AAA/Abc.jpg  can able to be identified as /xxx/aaa/abc.jpg.

but in Questopia，it will report an error

**Comment by l3ger0j** [comment]
Try the new version of Questopia!

https://github.com/l3ger0j/Questopia/releases/tag/3.21.2

**Comment by iceberg2271** [comment]
The problem still exists，When I open image debug，it‘s show that image file cannot be found:/avator.
Actually，the filename is Avator. use the 3.21.4

**Comment by iceberg2271** [comment]
> Try the new version of Questopia!
> 
> https://github.com/l3ger0j/Questopia/releases/tag/3.21.2

The problem still exists，When I open image debug，it‘s show that image file cannot be found:/avator.
Actually，the filename is Avator. use the 3.21.4
