### ISSUE TITLE
no addtional description display

### ISSUE THREAD

**Issue by nanocall** [l3ger0j/Questopia#44]
![Screenshot_2024-04-19-22-42-17-679_org qp android](https://github.com/l3ger0j/Questopia/assets/55532643/879d2c2b-bb52-4e1a-aa53-a55b37a60eac)
![Image_1713537802200](https://github.com/l3ger0j/Questopia/assets/55532643/17f0da90-0eac-4d20-aac5-76d6276926f0)
It's that because I play the Chinese version?

**Comment by l3ger0j** [comment]
No, and most likely all this has already been fixed in a newer version.

The reason for this bug is probably that this game is developed for the Sonnix engine, and Questopia uses the "official" 5.7.0 engine.
